checkout/urls.py
from django.urls import path
from .views import checkout, generate_invoice_in_cabinet

app_name = 'checkout'

urlpatterns = [
    path('checkout/', checkout, name='index'),
    path('<int:order_code>/generate_invoice_in_cabinet/', generate_invoice_in_cabinet, name='generate_invoice_in_cabinet'),
    # path('checkout_success/', checkout_success, name='checkout_success'),
]

core/urls.py
from django.urls import path
from django.conf.urls import url
from .views import HomeView, OrderSummaryView, contacts, conditions, search_view, specorder, my_cabinet, set_language, autocomplete


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('contacts', contacts, name='contacts_page'),
    path('conditions', conditions, name='conditions_page'),
    path('specorder', specorder, name='specorder'),
    path('search/', search_view, name='search_results'),
    path('my_cabinet', my_cabinet, name='my_cabinet'),
    path('set_language', set_language, name='set_language'),
    url(r'^ajax_calls/search/', autocomplete)
]

parts_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from .views import (category_detail, subcategory_detail, item_detail,
                    add_to_cart, remove_from_cart, remove_single_item_cart,
                    edit_account, update_cart_item_quantity)


admin.site.site_header = "BIG AGRO PARTS: панель адміністратора"
admin.site.site_title = "BIG AGRO PARTS: портал адміністратора"
admin.site.index_title = "Ласкаво просимо до адмінпанелі"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('checkout.urls', namespace='checkout')),
    path('accounts/', include('allauth.urls')),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('subcategory/<slug:slug>/', subcategory_detail, name='subcategory_detail'),
    path('items/<slug:slug>', item_detail, name='item_detail'),
    path('update_cart_item_quantity', update_cart_item_quantity, name='update_cart_item_quantity'),
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug:slug>/',
         remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_cart/<slug:slug>/',
         remove_single_item_cart, name='remove_single_item_cart'),
    path('', include('core.urls', namespace='core')),
    path('edit/', edit_account, name='edit_account'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

checkout/models.py
import locale
from datetime import datetime

from django.db import models
from django.contrib.auth import get_user_model
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _

from core.models import Item, Cart


User = get_user_model()


class Order(models.Model):

    NOVA_POSHTA = 'NP'
    KURIER = 'KU'
    DELIVERY_METHODS = (
        (NOVA_POSHTA, _('Нова Пошта')),
        (KURIER, _("Кур'єр (по м. Луцьк)"))
    )
    PAY_AFTER_DELIVERING = 'PAD'
    PAY_BEFORE_DELIVERING = 'PBD'
    PAYMENT_METHODS = (
        (PAY_AFTER_DELIVERING, _('Оплата при отриманні')),
        (PAY_BEFORE_DELIVERING, _('Оплата за реквізитами (передоплата)'))
    )

    total_price = models.CharField(verbose_name=_('Сума замовлення'), max_length=100)
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE, related_name='order', verbose_name='Код замовлення/Кошик')
    delivery_method = models.CharField(verbose_name=_('Метод доставки:'), choices=DELIVERY_METHODS, max_length=5, default=NOVA_POSHTA)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    customer_name = models.CharField(verbose_name=_('ПІБ покупця'), max_length=200)
    nova_poshta = models.CharField(max_length=5, verbose_name=_('№ відділення Нової Пошти'), help_text=_("Введіть лише число без '№'"), blank=True)
    city = models.CharField(max_length=100, verbose_name=_('Місто / село'), blank=True)
    address = models.CharField(max_length=200, verbose_name=_('Адреса для доставки по Луцьку'), blank=True)
    landmark = models.CharField(max_length=100, verbose_name=_('Область'), blank=True)
    phone = PhoneNumberField(verbose_name=_('Контактний номер телефону'))
    email = models.EmailField(verbose_name=_('Адреса електронної пошти'), max_length=200)
    payment_method = models.CharField(verbose_name=_('Метод оплати'), choices=PAYMENT_METHODS, max_length=10, default=PAY_BEFORE_DELIVERING)

    def generate_invoice_context(self, request):

        locale.setlocale(locale.LC_ALL, 'uk_UA.utf8')
        now = datetime.now()
        dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
        context = {
            'deliver': request.get_host(),
            'bayer': self.customer_name,
            'bayer_info': self.delivery_method,
            'time': dt_string,
            'cart': self.cart,
            'order_items': self.cart.items.all(),
            'order_code': self.cart.id,
            'order_total': self.total_price,
            'item_count': len(self.cart.items.all()),
        }
        return context

    def __str__(self):
        return f'order #{self.id}'

    class Meta:
        verbose_name_plural = 'Замовлення'

checkout/forms.py
from django.forms import ModelForm
from .models import Order
from django.utils.translation import gettext_lazy as _


class BillingForm(ModelForm):
    class Meta:
        model = Order
        fields = ['delivery_method', 'nova_poshta', 'customer_name', 'address', 'city', 'landmark', 'phone', 'email', 'payment_method']

checkout/views.py
from django.http.response import HttpResponse
from django.utils import timezone
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required

from xhtml2pdf import pisa

from .forms import BillingForm
from .models import Order
from core.models import Cart
from .admin import link_callback


def checkout(request):
    user = get_user(request)
    ordered_date = timezone.now()
    cart_id = request.session.get('cart_id')
    initial = {}
    if user.is_authenticated:
        initial = {
            'email': user.email,
            'phone': user.phone_number}
        if user.second_name:
            initial['customer_name'] = user.last_name + ' ' + user.first_name + ' ' + user.second_name
    form = BillingForm(initial=initial)

    cart_qs = Cart.objects.filter(id=cart_id, ordered=False)
    if len(cart_qs) != 0:
        cart = cart_qs[0]
        order_code = cart.id
        order_items = cart.items.all()
        order_total = cart.get_total()
        context = {
            'form': form,
            'order_items': order_items,
            'order_total': order_total,
            'order_code': order_code
        }
    else:
        return redirect('/')

    if request.method == 'POST':
        form = BillingForm(request.POST)
        if form.is_valid():
            print('form valid')
        order = Order()
        order.user = request.user if user.is_authenticated else None
        order.cart = cart
        order.total_price = order_total
        order.delivery_method = form.data['delivery_method']
        order.nova_poshta = form.data['nova_poshta']
        order.customer_name = form.data['customer_name']
        order.city = form.data['city']
        order.landmark = form.data['landmark']
        order.phone = form.data['phone']
        order.email = form.data['email']
        order.address = form.data['address']
        order.payment_method = form.data['payment_method']
        print(form.data['payment_method'])
        print(form.data['delivery_method'])
        order.save()
        cart.ordered = True
        cart.ordered_date = ordered_date
        cart.order_status = Cart.ORDER_ACCEPTED
        cart.save()

        return render(request, 'checkout_success.html')

    return render(request, 'index.html', context)


@login_required
def generate_invoice_in_cabinet(request, *args, **kwargs):
    # user = get_user(request)
    order_code = kwargs['order_code']
    order = Order.objects.get(cart_id=order_code)

    template_path = 'pdf/sales-invoice.html'
    context = order.generate_invoice_context(request)
    bayer = context['bayer']
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="invoice_orderid_{order_code}_user_{bayer}.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create PDF
    pisa_status = pisa.CreatePDF(
        html,
        dest=response,
        link_callback=link_callback,
    )

    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse(f'We had some errors <pre>{html}</pre>')

    return response

checkout/templates/checkout_success.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="container col-10" style="margin-top: 100px; margin-bottom: 300px">
    <div class="text-center">
        <h2 class="mb-3">{% trans 'Вітаємо!' %}<br>{% trans 'Ваше замовлення прийнято, вам може зателефонувати менеджер для його уточнення чи підтвердження. ' %}<br>{% trans 'Ми раді будемо бачити Вас знову!' %}</h2>
    </div>
</div>
{% endblock content %}

checkout/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}
<div class="container col-10" style="margin-top: 100px;">
    <h2 class="mb-3">{% trans 'Оформлення замовлення' %}</span></h2>
    <p>{% trans 'Оберіть спосіб доставки, вкажіть необхідні дані та спосіб оплати' %} </p>
    <div class="row">
      <div class="col-md-7">
       <div class="card mb-5" style="height: auto">
         <div class="card-body">
            <form method="POST">
            {% csrf_token %}
  
           {{ form | crispy}}

           
           <p class="detail_PBD">{% trans 'Після оформлення замовлення з Вами зв’яжеться наш оператор і надішле реквізити для оплати суми замовлення на карту Приватбанку.' %}</p>
           <p class="detail_PAD">{% trans 'Замовлення, оформлені як накладений платіж, оплачуються та отримуються на зручному для Вас відділенні «Нової пошти». При цьому отримувач має сплатити також додаткову поштову комісію за користування послугою післяплати. Якщо ж ви обрали доставку кур’єром по м. Луцьк, то оплату прийме кур’єр.' %}</p>
           <p>{% trans 'Вам може зателефонувати менеджер для уточнення чи підтвердження замовлення.' %}</p>
           <a href="{% url 'core:order-summary' %}" class="btn btn-warning">{% trans 'Повернутися до кошика' %}</a>
            <button type="submit" class="btn btn-primary float-right">{% trans 'Підтвердити замовлення' %}</button>
            </form>
         </div>
       </div>

      </div>
      <div class="col-md-5">
        <div class="card" style="height: auto">
          <div class="card-header">
            <span class="float-left"><b>{% trans 'Сума замовлення' %}:</b></span>
            <span class="float-right"><b>$ {{ order_total | floatformat:2 }}</b></span>
          </div>
          <div class="card-body">
            {% trans 'Ваше замовлення' %}: <hr>
            {% for order_item in order_items %}
              <div class="card">
                <div class="card-body">
                  <p class="card-title m-0"><strong><a href="{{ order_item.item.get_absolute_url }}" class="card-link">{{ order_item.item.title }}</a></strong></p><span>{% trans 'Кількість' %}: {{ order_item.quantity }}</span>
                  <p class="card-text">
                  {% trans 'Артикул' %}:
                    {{ order_item.item.item_code }} <br>
                  {% trans 'Ціна' %}:
                    ₴ {{ order_item.item_price }}
                  </p>
                  <p class="card-text">{% trans 'Сума' %}:
                    ₴ {{ order_item.get_final_price }}
                  </p>
                </div>
              </div>
           {% endfor %}
          </div>
          
        </div>
      </div>
    </div>
  </div>
{% endblock content %}