checkout/urls.py
from django.urls import path
from .views import checkout, generate_invoice_in_cabinet

app_name = 'checkout'

urlpatterns = [
    path('checkout/', checkout, name='index'),
    path('<int:order_code>/generate_invoice_in_cabinet/', generate_invoice_in_cabinet, name='generate_invoice_in_cabinet'),
    # path('checkout_success/', checkout_success, name='checkout_success'),
]

core/urls.py
from django.urls import path
from django.conf.urls import url
from .views import HomeView, OrderSummaryView, contacts, conditions, search_view, specorder, my_cabinet, set_language, autocomplete


app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('contacts', contacts, name='contacts_page'),
    path('conditions', conditions, name='conditions_page'),
    path('specorder', specorder, name='specorder'),
    path('search/', search_view, name='search_results'),
    path('my_cabinet', my_cabinet, name='my_cabinet'),
    path('set_language', set_language, name='set_language'),
    url(r'^ajax_calls/search/', autocomplete)
]

parts_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from .views import (category_detail, subcategory_detail, item_detail,
                    add_to_cart, remove_from_cart, remove_single_item_cart,
                    edit_account, update_cart_item_quantity)


admin.site.site_header = "BIG AGRO PARTS: панель адміністратора"
admin.site.site_title = "BIG AGRO PARTS: портал адміністратора"
admin.site.index_title = "Ласкаво просимо до адмінпанелі"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('checkout.urls', namespace='checkout')),
    path('accounts/', include('allauth.urls')),
    path('category/<slug:slug>/', category_detail, name='category_detail'),
    path('subcategory/<slug:slug>/', subcategory_detail, name='subcategory_detail'),
    path('items/<slug:slug>', item_detail, name='item_detail'),
    path('update_cart_item_quantity', update_cart_item_quantity, name='update_cart_item_quantity'),
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<slug:slug>/',
         remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_cart/<slug:slug>/',
         remove_single_item_cart, name='remove_single_item_cart'),
    path('', include('core.urls', namespace='core')),
    path('edit/', edit_account, name='edit_account'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

core/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
import re
from django.utils.translation import gettext as _
from phonenumber_field.modelfields import PhoneNumberField


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(max_length=150, blank=False, verbose_name="Ім'я")
    second_name = models.CharField(max_length=150, blank=True, null=True, verbose_name=_("Ім'я по батькові"))
    last_name = models.CharField(max_length=150, blank=False)
    email = models.EmailField(_('email address'), unique=True)
    phone_number = PhoneNumberField(verbose_name='Phone Number', help_text=_("Має починатися з +380"), blank=True, null=True)
    # company = models.CharField(verbose_name='Компанія, яку представляє', max_length=150, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True, editable=True)
    wholesaler = models.BooleanField(default=False, verbose_name='Статус оптовика')

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

    class Meta:
        verbose_name = _("Користувач")
        verbose_name_plural = _("Користувачі")

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Category(models.Model):
    title = models.CharField(max_length=100, null=True)
    image = models. ImageField(verbose_name='Фото категорії', upload_to='uploads/category_images', default='None/category.jpg', blank=True, null=True)
    slug = AutoSlugField(populate_from='title',
                         unique=True,
                         allow_unicode=True,
                         max_length=200,
                         null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = "Категорії"
        ordering = ('id',)


class SubCategory(models.Model):
    title = models.CharField(max_length=200)
    image = models. ImageField(verbose_name='Фото підкатегорії', upload_to='uploads/sub_category_images', default='None/subcategory.jpg', blank=True, null=True)
    slug = AutoSlugField(populate_from='title',
                         unique=True,
                         allow_unicode=True,
                         max_length=200,
                         null=True)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('subcategory_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = "Підкатегорії"
        ordering = ('title',)


class Item(models.Model):

    AVAILABLE = '1'
    NOT_AVAILABLE = '0'
    NEED_TO_CHECK = '2'

    AVAILABILITY_CHOICES = (
        (AVAILABLE, _('Є в наявності')),
        (NOT_AVAILABLE, _('Немає в наявності')),
        (NEED_TO_CHECK, _('Уточніть наявність'))
    )

    title = models.CharField(max_length=200, verbose_name='Назва')
    # image = models.ImageField(verbose_name='Фото деталі', upload_to='uploads/', default='/None/item.jpg', blank=True, null=True)
    item_code = models.CharField(max_length=100, blank=True, verbose_name='Артикул', null=True)
    description = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Опис')
    price = models.FloatField(max_length=200, verbose_name='Ціна')
    availability = models.CharField(choices=AVAILABILITY_CHOICES, default=AVAILABLE, verbose_name='Наявність', max_length=20)
    wholesaler_price = models.FloatField(max_length=200, verbose_name='Оптова ціна')
    add_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення', null=True, blank=True)
    slug = AutoSlugField(populate_from='title',
                         unique=True,
                         max_length=200,
                         allow_unicode=True,
                         null=True)
    subcategories = models.ManyToManyField(SubCategory, blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    class Meta:
        verbose_name_plural = 'Товари'
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('item_detail', kwargs={'slug': self.slug})

    def get_add_to_card_url(self):
        return reverse('add_to_cart', kwargs={'slug': self.slug})

    def get_remove_from_card_url(self):
        return reverse('remove_from_cart', kwargs={'slug': self.slug})


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='Фото деталі', upload_to='uploads/', default='None/item.jpg', blank=True, null=True)
    default = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'Image #{self.id} for {self.item.title}'

    class Meta:
        verbose_name_plural = 'Фото товарів'


class CartItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, verbose_name='Користувач', blank=True, null=True)
    cart_id = models.IntegerField(verbose_name='ID кошика', default=0)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, verbose_name='Товар')
    item_price = models.FloatField(max_length=200, verbose_name='Вартість товару', blank=True, default=0.0)
    quantity = models.IntegerField(default=1, verbose_name='Кількість')
    ordered = models.BooleanField(default=False, verbose_name='Замовлення підтверджено')

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        total = float(self.item_price * self.quantity)
        return total

    def get_final_price(self):
        return self.get_total_item_price()

    class Meta:
        verbose_name_plural = "Товари в кошику"
        ordering = ('id',)


class Cart(models.Model):

    LEFTED_CART = 'LC'
    ORDER_ACCEPTED = 'OA'
    ORDER_IS_PROCESSED = 'OIP'
    ORDER_FULLFILED = 'OF'

    ORDER_STATUS_CHOICES = (
        (LEFTED_CART, _('Залишений кошик')),
        (ORDER_ACCEPTED, _('Замовлення прийнято')),
        (ORDER_IS_PROCESSED, _('Замовлення виконується')),
        (ORDER_FULLFILED, _('Замовлення виконано'))
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, verbose_name='Користувач', blank=True, null=True)
    items = models.ManyToManyField(CartItem, verbose_name='Товари')
    start_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата формування')
    ordered_date = models.DateTimeField(verbose_name='Дата замовлення', null=True, blank=True)
    ordered = models.BooleanField(default=False, verbose_name='Замовлення підтверджено')
    order_total_price = models.FloatField(max_length=200, verbose_name='Вартість замовлення', blank=True, default=0.0)
    order_status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name=_('Статус замовлення'), default=LEFTED_CART, max_length=20)

    def __str__(self):
        return 'Кошик: ' + str(self.id)

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
            self.order_total_price = total
        return total

    def set_total(self):
        self.order_total_price = self.get_total()

    class Meta:
        verbose_name_plural = "Кошик"

templates/home-page.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

  <!--First slide-->
    <div class="carousel-item active">
      <div class="view" style="background-image: url('{% static 'img/coop.png' %}'); background-repeat: no-repeat; background-size: cover; background-position: center;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h3 class="mb-4">
              <strong>{% trans 'Ви представник фірми чи оптовик?' %}</strong>
            </h3>

            <p class="mb-4">
              <strong>{% trans 'Зареєструйтеся та зверніться до нас і ми надамо вам знижку!' %}</strong>
            </p>
            <p>
              <strong class="green-text">BIG AGRO</strong><strong class="white-text"> PARTS</strong>
            </p>

            <a href="/contacts" class="btn btn-outline-white btn-lg slider-btn">{% trans 'КОНТАКТИ' %}
              <i class="fas fa-phone ml-2"></i>
            </a>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/First slide-->

    <!--Second slide-->
    <div class="carousel-item">
      <div class="view" style="background-image: url('{% static 'img/logo_multi.png' %}'); background-repeat: no-repeat; background-size: cover; background-position: center;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong class="yellow-text">{% trans 'Не знайшли в каталозі потрібну вам деталь?' %}</strong>
            </h1>

            <p>
              <strong >{% trans 'Ви можете скористатися функцією "Спецзамовлення".' %}</strong>
            </p>

            <p class="mb-4">
              <strong>{% trans 'Просто зателефонуйте нам і повідомте яка деталь вам потрібна.' %}</strong>
            </p>

            <a href="/specorder" class="btn btn-outline-white btn-lg slider-btn">{% trans 'Спецзамовлення' %}
              <i class="fas fa-magic ml-2"></i>
            </a>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div class="view" style="background-image: url('{% static 'img/MILTI_LOGOS23.png' %}'); background-repeat: no-repeat; background-size: cover; background-position: center;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong class="green-text">BIG AGRO</strong><strong class="white-text"> PARTS</strong>
            </h1>
            <p class="mb-4">
              <strong>{% trans 'Величезний каталог запчастин до сільськогосподарської техніки' %}</strong>
            </p>
            <p class="mb-4">
              <strong>{% trans 'Тут ви знайдете все, що вам потрібно!' %}</strong>
            </p>

            <a href="#containerMain" class="btn btn-outline-white btn-lg slider-btn">
              <i class="fas fa-angle-double-down"></i>
            </a>
          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/Third slide-->

  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">{% trans 'Попередній' %}</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">{% trans 'Наступний' %}</span>
  </a>
  <!--/.Controls-->
  
</div>
<!--/.Carousel Wrapper-->

<!--Main layout-->
<main>
  <div class="container {% if category_items or subcategory_items or item_items %} col-11{% endif %}" id="containerMain">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color success-color-dark mt-3 mb-5" style="border-radius: 5px;">
        <form id="search" action="{% url 'core:search_results' %}" class="form-inline w-100" method="POST">
          {% csrf_token %}
          <div class="md-form my-0 w-100">
            <input class="form-control w-100 m-0" id="q" name="q" type="text" placeholder="{% trans 'Введіть назву запчастини чи її артикул та натисніть Enter' %}" aria-label="Search" title="{% trans 'Намагайтесь вводити точну назву чи артикул' %}">
          </div>
        </form>
    </nav>
    <section class="text-center mb-4">
      
      {% if category_items %}
        <h5 class="p-4">{% trans 'Категорії за запитом' %} <strong>"{{ query }}"</strong>:</h5>
        <div class="row">
        {% for category in category_items %}
        <div class="col-6 col-lg-3 col-md-4 mb-4">
          <div class="card card-item">
            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <div class="img-title-box">
                <a href="{{category.get_absolute_url }}" class="card-link">
                  <div class="card-img-box">
                    <img src="{{ category.image.url }}" alt="" class="card-img-top">
                  </div>
                  <div class="card-title-box">
                    <h5>{{ category.title }}</h5>
                  </div>
                </a>
              </div>
              <div class="card-btn-box">
                <a href="{{ category.get_absolute_url }}" class="btn btn-success">{% trans 'Перейти' %}</a> 
              </div>
            </div>
            <!--Card content-->
          </div>
        </div>
        {% endfor %}
        </div>
      {% endif %}

      {% if subcategory_items %}
        <h5 class="p-4">{% trans 'Підкатегорії за запитом' %} <strong>"{{ query }}"</strong>:</h5>
        <div class="row">
        {% for subcategory in subcategory_items %}
        <div class="col-6 col-lg-3 col-md-4 mb-4">
          <div class="card card-item">
              <div class="card-body">
                <div class="img-title-box">
                  <a href="{{ subcategory.get_absolute_url }}" class="card-link">
                    <div class="card-img-box">
                      <img src="{{ subcategory.image.url }}" alt="" class="card-img-top">
                    </div>
                    <div class="card-title-box">
                      <p>{{ subcategory.title }}</p>
                    </div>
                  </a>
                </div>
                <div class="card-btn-box">
                  <a href="{{ category.get_absolute_url }}" class="btn btn-success">{% trans 'Перейти' %}</a> 
                </div>
              </div>
          </div>
        </div>
        {% endfor %}
        </div>
      {% endif %}

      {% if item_items %}
        <h5 class="p-4">{% trans 'Товари за запитом' %} <strong>"{{ query }}"</strong>:</h5>
        <div class="row">
        {% for item in item_items %}
          {% include 'elements/item-element.html' %}
        {% endfor %}
        </div>
      {% endif %}

      {% if not category_items and not subcategory_items and not item_items and not object_list %}
      <h5 class="m-5">{% trans 'Нажаль  за запитом' %} <strong>"{{ query }}"</strong> {% trans 'нічого не знайдено, спробуйте виправити запит' %}<br> {% trans 'або зверніть увагу на функцію' %} <big><a href="{% url 'core:specorder' %}" class="badge badge-success"> {% trans 'спецзамовлення' %}</a></big></h5>
      {% endif %}
    
      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        
        {% for category in object_list %}
          <div class="col-6 col-lg-3 col-md-4 mb-4">
            <div class="card card-item">
              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <div class="img-title-box">
                  <a href="{{category.get_absolute_url }}" class="card-link">
                    <div class="card-img-box">
                      <img src="{{ category.image.url }}" alt="" class="card-img-top">
                    </div>
                    <div class="card-title-box">
                      <h5>{{ category.title }}</h5>
                    </div>
                  </a>
                </div>
                <div class="card-btn-box">
                  <a href="{{ category.get_absolute_url }}" class="btn btn-success">{% trans 'Перейти' %}</a> 
                </div>
              </div>
              <!--Card content-->
            </div>
          </div>
        {% endfor %}
          

      </div>
    </section>
  </div>
      

      
    


    <!-- Pagination-->
    <!-- <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue"> -->

        <!--Arrow left-->
        <!-- <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>

        <li class="page-item active">
          <a class="page-link" href="#">1
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav> -->
    <!--Pagination -->

  </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/product-page.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container dark-grey-text">

    <!--Grid row-->
    <div class="row wow fadeIn mb-5">

      <!--Grid column-->
      <div class="col-md-6">
        <!--Carousel Wrapper-->
        <div id="carousel-example-1z" class="carousel slide carousel-fade " data-ride="carousel" style="height: auto;!important">
          <!--Indicators-->
          <ol class="carousel-indicators">
            {% for i in item_images %}
              <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter0 }}" class="green {% if forloop.counter0 == 0 %} active {% endif %}"></li>
            {% endfor %}
          </ol>
          <!--/.Indicators-->
          <!--Slides-->
          <div class="carousel-inner" role="listbox">
            {% for i in item_images %}
            <div class="mt-5 pt-5 carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
              <img class="img-fluid" src="{{i.image.url}}"
                alt="First slide">
            </div>
            {% endfor %}
            <!--/First slide-->
            <!--/.Slides-->
            <!--Controls-->
            <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon green" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
              <span class="carousel-control-next-icon green" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          <!--/.Controls-->
        </div>
      </div>



      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mt-5 pt-5">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="{{ category.get_absolute_url }}">
              <span class="badge purple mr-1">{{ category.title }}</span>
            </a>
            <a href="{{ subcategory.get_absolute_url }}">
              <span class="badge purple mr-1">{{ subcategory.title }}</span>
            </a>
            {% if item.availability == '1' %}
              <span class="badge green mr-1">{% trans item.get_availability_display %}</span>
            {% elif item.availability == '0' %}
              <span class="badge red mr-1">{% trans item.get_availability_display %}</span>
            {% elif item.availability == '2' %}
              <span class="badge badge-warning mr-1">{% trans item.get_availability_display %}</span>
            {% endif %}
            
          </div>

          
          <p class="lead font-weight-bold">{{ item.title }}</p>
          <p class="lead"><hr>
            {% if item.availability != '0' %}
              {% if request.user.wholesaler %}
                <span class="product_page_price">{% trans 'Ціна' %}: ₴ {{ item.wholesaler_price }}</span>
              {% else %}  
                <span class="product_page_price">{% trans 'Ціна' %}: ₴ {{ item.price }}</span>
              {% endif %}
            {% endif %}
          </p>
          <p><small>{% trans 'Артикул' %}: <b>{{ item.item_code }}</b></small></p>
          <p>{% trans 'Код товару' %}: <b>{{ item.id }}</b></p>

          <div class="product_page_buttons mt-4">
            {% if item.availability == '1' %}
              <a href="{{ item.get_add_to_card_url }}" class="btn btn-success btn-md my-0 p" >{% trans 'Додати в кошик' %}
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              <a href="{{ item.get_remove_from_card_url }}" class="btn btn-danger btn-md my-0 p" >{% trans 'Видалити з кошика' %}
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
            {% elif item.availability == '0' %}
              <span class="mr-1">{% trans 'Цього товару немає в наявності зараз' %}. <a href="/contacts">{% trans 'Зателефонуйте нам' %}</a>, {% trans 'аби уточнити коли він буде доступний.' %}</span> <br>
              <a href="{% url 'core:contacts_page' %}" class="btn btn-warning btn-md mt-3 my-0 p" ><b>{% trans 'Уточнити наявність' %}</b></a>
            {% else %}
              <span class="mr-1">{% trans 'Цей товар закінчується' %}. <br><a href="/contacts">{% trans 'Зателефонуйте нам' %}</a>, {% trans 'аби уточнити його наявність.' %}</span><br>
              <a href="{% url 'core:contacts_page' %}" class="btn btn-warning btn-md mt-3 my-0 p" ><b>{% trans 'Уточнити наявність' %}</b></a>
            {% endif %}
          </div>
          <div class="product_page_description">
            {% if item.description != None %}
              <div class="description mt-5">
                <h4>{% trans 'Опис' %}:</h4>
                <p>{{ item.description }}</p>
              </div>
            {% endif %}
          </div>
        </div>
        <!--Content-->
        
      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->
    
    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">{% trans 'Інші товари з цього розділу' %}: </h4>
      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row">

      {% for item in last_items %}
        {% include 'elements/item-element.html' %}
      {% endfor %}


    </div>
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->

{% endblock content %}